name: Run TOATCH1609 Daily

on:
  schedule:
    - cron: '0 7 * * *' # 04:00 hora Chile (UTC-3, por eso 07:00 UTC)
  workflow_dispatch: # permite ejecutar manualmente desde GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium

      - name: Run TOATCH1609.py
        env:
          USUARIO_PORTAL: ${{ secrets.USUARIO_PORTAL }}
          PASS_PORTAL: ${{ secrets.PASS_PORTAL }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
          DOWNLOAD_FOLDER: /github/home
        run: |
          python TOATCH1609.py
