name: Ejecutar TOATCH1609

on:
  schedule:
    - cron: '59 16 * * *'  # 13:40 hora Chile (UTC-3)
  workflow_dispatch:   # permite ejecutarlo manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        env:
          USUARIO_PORTAL: ${{ secrets.USUARIO_PORTAL }}
          PASS_PORTAL: ${{ secrets.PASS_PORTAL }}
          OUTLOOK_PASS: ${{ secrets.OUTLOOK_PASS }}
        run: python toatch1609.py


